document.write('<h4>Features and Benefits</h4>');
document.write('<ul>');
document.write('<li>Lighter weight in comparison to fauxwood blinds</li>');
document.write('<ul>');
document.write('<li>Tighter closure</li>');
document.write('<li>Easier to raise</li>');
document.write('<li>Less wear of components</li>');
document.write('<li>Less ladders to obstruct view</li>');
document.write('</ul>');
document.write('<li>Light control via adjusting the tilt of slats</li>');
document.write('<li>A variety of slat sizes: 1", 2", 2.5" (least obstructed view)</li>'); 
document.write('<li>High thermal insulation to impede flow of heat</li>');
document.write('<li>Good privacy</li>');
document.write('<li>Warmth and elegance of wood in stain color choices</li>');
document.write('</ul>');
document.write('<h4>Options</h4>');
document.write('<ul>');
document.write('<li>Routless slats</li>');
document.write('<ul>');
document.write('<li>Cleaner look</li>');
document.write('<li>Greater light control, privacy</li>');
document.write('<li>Easy slat replacement</li>');
document.write('</ul>');
document.write('<li>Fabric tape to soften the look, add color to the room, and to coordinate blind with other colors in the room</li>');
document.write('<li>Cord tilt instead of wand tilt for a cleaner look, easier operation, and longer component life</li>');
document.write('<li>Variety of choices for carved decorative valances to hide the headrail of the blind. Taller valances provide greater light control and privacy</li>');
document.write('<li>cordless lift system</li>');
document.write('<li>motorized tilt system</li>');
document.write('</ul>');

