document.write('<div class="sticky">');
document.write("<p style='text-align: center; margin-bottom: 0px;'>");
document.write("<a href="+mainPageProfile+"><button class='menuButton'>Home</button></a>&nbsp;&nbsp;&nbsp;");
document.write("<a href="+awardsPage+"><button class='menuButton'>Awards</button></a>&nbsp;&nbsp;&nbsp;");
//document.write("<a href="+webProjectPage+">Programming Portfolio</a>&nbsp;&nbsp;&nbsp;");
document.write("<a href="+programmingExperience+"><button class='menuButton'>Programming Experience</button></a>&nbsp;&nbsp;&nbsp;");
document.write("<a href="+coursework+"><button class='menuButton'>Coursework</button></a>&nbsp;&nbsp;&nbsp;");
document.write("<a href='mailto:waqar.mahmood.pro@gmail.com'><button class='menuButton'>Contact</button></a>&nbsp;&nbsp;&nbsp;");
document.write("</p>");
document.write('</div>');